name: WindoesCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
env:
  DOTNETVERSION: 6.0.400
  BASE64_KYESTORE: ./android/release.keystore.base64
  DECRYPTED_KEYSTORE: ./android/release.decrypted.keystore

jobs:
  buildAndroid:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '${{env.DOTNETVERSION}}'

      - name: List installed .NET info
        shell: pwsh
        run: dotnet --info
        
      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet nuget locals all --clear
          dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          
      - name: Restore nuget packages
        run: dotnet restore ./DotnetMauiApp/DotnetMauiApp.csproj
        
      - name: Extract Android signing key from env
        shell: bash
        run: |
          mkdir -p android
          echo "${{ secrets.RELEASE_KEYSTORE }}" > "${{ env.BASE64_KYESTORE }}"
          base64 -d "${{ env.BASE64_KYESTORE }}" > "${{ env.DECRYPTED_KEYSTORE }}"
        
      - name: Build Android App
        shell: bash
        run: |
          dotnet publish ./DotnetMauiApp/DotnetMauiApp.csproj -f:net6.0-android -c:Release /p:AndroidSigningKeyPass="${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" /p:AndroidSigningKeyStore=../"${{ env.DECRYPTED_KEYSTORE }}" /p:AndroidSigningKeyAlias=key
        
#       - name: Sign dev build
#         shell: bash
#         run: jarsigner -keystore android/release.decrypted.keystore -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./DotnetMauiApp/bin/Release/net6.0-android/publish/*Signed.aab key

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-android
          path: ./DotnetMauiApp/bin/Release/net6.0-android/publish/*.apk
          
